### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by heilyy** [hjcian/CNN-LSTM-phishing-detection#1]
Hello, could you please publish the data set? I would appreciate it.

**Comment by hjcian** [comment]
Hi @heilyy,

The phishing data is come from Phishtank: https://phishtank.org/developer_info.php, 
a very popular phishing dataset provider.

However, the legitimate URLs come from my company's private dataset, so these data can not be shared with the public.

**Comment by heilyy** [comment]
Thank you very much for your help, but I would like to ask whether the data of this project you reproduced is the data of the original paper or your own private data?

**Comment by heilyy** [comment]
Thank you very much for your help, but I would like to ask whether the data of this project you reproduced is the data of the original paper or your own private data?

**Comment by hjcian** [comment]
@heilyy Yes, we just use our own private data to do the experiment.
